namespace ObjMapper.Services.Pluralization;

/// <summary>
/// German irregular plurals dictionary.
/// </summary>
public sealed class GermanIrregulars : IrregularDictionary
{
    private static readonly Lazy<GermanIrregulars> _instance = new(() => new GermanIrregulars());
    public static GermanIrregulars Instance => _instance.Value;

    private readonly Dictionary<string, string> _singularToPlural = new(StringComparer.OrdinalIgnoreCase)
    {
        // Umlaut changes (a -> ä, o -> ö, u -> ü)
        { "Apfel", "Äpfel" },
        { "Bruder", "Brüder" },
        { "Garten", "Gärten" },
        { "Hafen", "Häfen" },
        { "Laden", "Läden" },
        { "Magen", "Mägen" },
        { "Mantel", "Mäntel" },
        { "Nacht", "Nächte" },
        { "Nagel", "Nägel" },
        { "Ofen", "Öfen" },
        { "Sattel", "Sättel" },
        { "Schaden", "Schäden" },
        { "Schnabel", "Schnäbel" },
        { "Schwager", "Schwäger" },
        { "Vater", "Väter" },
        { "Vogel", "Vögel" },
        
        // -e plurals with umlaut
        { "Arzt", "Ärzte" },
        { "Bach", "Bäche" },
        { "Bank", "Bänke" },
        { "Bart", "Bärte" },
        { "Baum", "Bäume" },
        { "Block", "Blöcke" },
        { "Bock", "Böcke" },
        { "Brust", "Brüste" },
        { "Busch", "Büsche" },
        { "Dach", "Dächer" },
        { "Darm", "Därme" },
        { "Fach", "Fächer" },
        { "Fall", "Fälle" },
        { "Fluss", "Flüsse" },
        { "Frosch", "Frösche" },
        { "Fuchs", "Füchse" },
        { "Fuß", "Füße" },
        { "Gans", "Gänse" },
        { "Gast", "Gäste" },
        { "Gruft", "Grüfte" },
        { "Grund", "Gründe" },
        { "Halt", "Hälfte" },
        { "Hand", "Hände" },
        { "Hals", "Hälse" },
        { "Hut", "Hüte" },
        { "Kamm", "Kämme" },
        { "Kampf", "Kämpfe" },
        { "Kauf", "Käufe" },
        { "Klang", "Klänge" },
        { "Koch", "Köche" },
        { "Kopf", "Köpfe" },
        { "Korn", "Körner" },
        { "Korb", "Körbe" },
        { "Kraft", "Kräfte" },
        { "Kuss", "Küsse" },
        { "Lauf", "Läufe" },
        { "Loch", "Löcher" },
        { "Luft", "Lüfte" },
        { "Markt", "Märkte" },
        { "Mund", "Münder" },
        { "Nuss", "Nüsse" },
        { "Platz", "Plätze" },
        { "Rand", "Ränder" },
        { "Raum", "Räume" },
        { "Rock", "Röcke" },
        { "Saft", "Säfte" },
        { "Satz", "Sätze" },
        { "Schatz", "Schätze" },
        { "Schloss", "Schlösser" },
        { "Schrank", "Schränke" },
        { "Schwanz", "Schwänze" },
        { "Sohn", "Söhne" },
        { "Sprung", "Sprünge" },
        { "Stamm", "Stämme" },
        { "Stand", "Stände" },
        { "Stock", "Stöcke" },
        { "Stoß", "Stöße" },
        { "Strumpf", "Strümpfe" },
        { "Stuhl", "Stühle" },
        { "Sturm", "Stürme" },
        { "Ton", "Töne" },
        { "Topf", "Töpfe" },
        { "Traum", "Träume" },
        { "Tuch", "Tücher" },
        { "Turm", "Türme" },
        { "Wald", "Wälder" },
        { "Wand", "Wände" },
        { "Wolf", "Wölfe" },
        { "Wort", "Wörter" },
        { "Wurm", "Würmer" },
        { "Zahn", "Zähne" },
        { "Zaun", "Zäune" },
        { "Zug", "Züge" },
        
        // -er plurals with umlaut
        { "Buch", "Bücher" },
        { "Dorf", "Dörfer" },
        { "Glas", "Gläser" },
        { "Haus", "Häuser" },
        { "Holz", "Hölzer" },
        { "Horn", "Hörner" },
        { "Huhn", "Hühner" },
        { "Kleid", "Kleider" },
        { "Rad", "Räder" },
        
        // Completely irregular
        { "Auge", "Augen" },
        { "Herz", "Herzen" },
        { "Bett", "Betten" },
        { "Hemd", "Hemden" },
        { "Ohr", "Ohren" },
        { "Staat", "Staaten" },
        
        // Foreign words
        { "Auto", "Autos" },
        { "Baby", "Babys" },
        { "Chef", "Chefs" },
        { "Computer", "Computer" },
        { "Hotel", "Hotels" },
        { "Kamera", "Kameras" },
        { "Laptop", "Laptops" },
        { "Park", "Parks" },
        { "Pizza", "Pizzen" },
        { "Sofa", "Sofas" },
        { "Taxi", "Taxis" },
        { "Team", "Teams" },
        
        // Computing terms
        { "Server", "Server" },
        { "Benutzer", "Benutzer" },
        { "Datei", "Dateien" },
        { "Ordner", "Ordner" },
        { "Datenbank", "Datenbanken" },
        { "Schnittstelle", "Schnittstellen" },
    };

    protected override Dictionary<string, string> SingularToPlural => _singularToPlural;
}
